/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiResumeExtractRouteImport } from './routes/api/resume-extract'
import { Route as ApiJobSearchRouteImport } from './routes/api/job-search'
import { Route as ApiJobChatRouteImport } from './routes/api/job-chat'
import { Route as AuthenticatedProfilesIndexRouteImport } from './routes/_authenticated/profiles.index'
import { Route as AuthenticatedProfilesIdRouteImport } from './routes/_authenticated/profiles.$id'
import { Route as AuthenticatedProfilesIdSearchRouteImport } from './routes/_authenticated/profiles.$id.search'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiResumeExtractRoute = ApiResumeExtractRouteImport.update({
  id: '/api/resume-extract',
  path: '/api/resume-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobSearchRoute = ApiJobSearchRouteImport.update({
  id: '/api/job-search',
  path: '/api/job-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobChatRoute = ApiJobChatRouteImport.update({
  id: '/api/job-chat',
  path: '/api/job-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilesIndexRoute =
  AuthenticatedProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilesIdRoute = AuthenticatedProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesIdSearchRoute =
  AuthenticatedProfilesIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedProfilesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/api/job-chat': typeof ApiJobChatRoute
  '/api/job-search': typeof ApiJobSearchRoute
  '/api/resume-extract': typeof ApiResumeExtractRoute
  '/profiles/$id': typeof AuthenticatedProfilesIdRouteWithChildren
  '/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/profiles/$id/search': typeof AuthenticatedProfilesIdSearchRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/api/job-chat': typeof ApiJobChatRoute
  '/api/job-search': typeof ApiJobSearchRoute
  '/api/resume-extract': typeof ApiResumeExtractRoute
  '/': typeof AuthenticatedIndexRoute
  '/profiles/$id': typeof AuthenticatedProfilesIdRouteWithChildren
  '/profiles': typeof AuthenticatedProfilesIndexRoute
  '/profiles/$id/search': typeof AuthenticatedProfilesIdSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/job-chat': typeof ApiJobChatRoute
  '/api/job-search': typeof ApiJobSearchRoute
  '/api/resume-extract': typeof ApiResumeExtractRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/profiles/$id': typeof AuthenticatedProfilesIdRouteWithChildren
  '/_authenticated/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/_authenticated/profiles/$id/search': typeof AuthenticatedProfilesIdSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/job-chat'
    | '/api/job-search'
    | '/api/resume-extract'
    | '/profiles/$id'
    | '/profiles/'
    | '/profiles/$id/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/api/job-chat'
    | '/api/job-search'
    | '/api/resume-extract'
    | '/'
    | '/profiles/$id'
    | '/profiles'
    | '/profiles/$id/search'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/api/job-chat'
    | '/api/job-search'
    | '/api/resume-extract'
    | '/_authenticated/'
    | '/_authenticated/profiles/$id'
    | '/_authenticated/profiles/'
    | '/_authenticated/profiles/$id/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiJobChatRoute: typeof ApiJobChatRoute
  ApiJobSearchRoute: typeof ApiJobSearchRoute
  ApiResumeExtractRoute: typeof ApiResumeExtractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/resume-extract': {
      id: '/api/resume-extract'
      path: '/api/resume-extract'
      fullPath: '/api/resume-extract'
      preLoaderRoute: typeof ApiResumeExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job-search': {
      id: '/api/job-search'
      path: '/api/job-search'
      fullPath: '/api/job-search'
      preLoaderRoute: typeof ApiJobSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job-chat': {
      id: '/api/job-chat'
      path: '/api/job-chat'
      fullPath: '/api/job-chat'
      preLoaderRoute: typeof ApiJobChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profiles/': {
      id: '/_authenticated/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AuthenticatedProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/$id': {
      id: '/_authenticated/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof AuthenticatedProfilesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/$id/search': {
      id: '/_authenticated/profiles/$id/search'
      path: '/search'
      fullPath: '/profiles/$id/search'
      preLoaderRoute: typeof AuthenticatedProfilesIdSearchRouteImport
      parentRoute: typeof AuthenticatedProfilesIdRoute
    }
  }
}

interface AuthenticatedProfilesIdRouteChildren {
  AuthenticatedProfilesIdSearchRoute: typeof AuthenticatedProfilesIdSearchRoute
}

const AuthenticatedProfilesIdRouteChildren: AuthenticatedProfilesIdRouteChildren =
  {
    AuthenticatedProfilesIdSearchRoute: AuthenticatedProfilesIdSearchRoute,
  }

const AuthenticatedProfilesIdRouteWithChildren =
  AuthenticatedProfilesIdRoute._addFileChildren(
    AuthenticatedProfilesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProfilesIdRoute: typeof AuthenticatedProfilesIdRouteWithChildren
  AuthenticatedProfilesIndexRoute: typeof AuthenticatedProfilesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProfilesIdRoute: AuthenticatedProfilesIdRouteWithChildren,
  AuthenticatedProfilesIndexRoute: AuthenticatedProfilesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiJobChatRoute: ApiJobChatRoute,
  ApiJobSearchRoute: ApiJobSearchRoute,
  ApiResumeExtractRoute: ApiResumeExtractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
